// This file is auto-generated by @hey-api/openapi-ts

export { getApiGuardias, getApiInventario, type Options } from './sdk.gen';
export type { ClientOptions, Entrada, GetApiGuardiasData, GetApiGuardiasResponse, GetApiGuardiasResponses, GetApiInventarioData, GetApiInventarioResponse, GetApiInventarioResponses, Guardia, InventarioItem, Salida } from './types.gen';
