// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiGuardiasData, GetApiGuardiasResponses, GetApiInventarioData, GetApiInventarioResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all guardias
 */
export const getApiGuardias = <ThrowOnError extends boolean = false>(options?: Options<GetApiGuardiasData, ThrowOnError>) => (options?.client ?? client).get<GetApiGuardiasResponses, unknown, ThrowOnError>({ url: '/api/guardias', ...options });

/**
 * Get total inventory calculations
 */
export const getApiInventario = <ThrowOnError extends boolean = false>(options?: Options<GetApiInventarioData, ThrowOnError>) => (options?.client ?? client).get<GetApiInventarioResponses, unknown, ThrowOnError>({ url: '/api/inventario', ...options });
