// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};

export type Guardia = {
    id: number;
    numero_elemento: string;
    nombre: string;
    estado: string | null;
    fecha_alta: string;
    fecha_baja: string | null;
};

export type Entrada = {
    id: number;
    fecha: string;
    articulo: string;
    talla: string | null;
    cantidad: number;
    estado: string;
    motivo: string;
    origen_devolucion: string | null;
    registrado_por: string | null;
};

export type Salida = {
    id: number;
    fecha: string;
    concepto: string;
    articulo: string;
    talla: string | null;
    cantidad: number;
    nombre_guardia: string | null;
    estado_asignacion: string | null;
    guardia_id: number | null;
};

export type InventarioItem = {
    articulo: string;
    totalEntradas: number;
    almacen: number;
    enCampo: number;
    enBajas: number;
    perdidas: number;
    totalExistente: number;
    stockBajo: boolean;
};

export type GetApiGuardiasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/guardias';
};

export type GetApiGuardiasResponses = {
    /**
     * List of guardias
     */
    200: Array<{
        id: number;
        numero_elemento: string;
        nombre: string;
        estado: string | null;
        fecha_alta: string;
        fecha_baja: string | null;
    }>;
};

export type GetApiGuardiasResponse = GetApiGuardiasResponses[keyof GetApiGuardiasResponses];

export type GetApiInventarioData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inventario';
};

export type GetApiInventarioResponses = {
    /**
     * Inventario array
     */
    200: Array<{
        articulo: string;
        totalEntradas: number;
        almacen: number;
        enCampo: number;
        enBajas: number;
        perdidas: number;
        totalExistente: number;
        stockBajo: boolean;
    }>;
};

export type GetApiInventarioResponse = GetApiInventarioResponses[keyof GetApiInventarioResponses];
